trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  webAppName: "360-api"
  azureServiceConnection: "Subscription 1 (a7b7fbd9-229d-44b7-8049-2f4cfa6b7bb1)"
  nodeLtsVersion: "22-lts"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "22.x"
    displayName: "Install Node.js LTS"

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "Archive project files"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
      publishLocation: "Container"
    displayName: "Publish Build Artifacts"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "$(azureServiceConnection)"
      appType: "webAppLinux"
      appName: "$(webAppName)"
      package: "$(System.DefaultWorkingDirectory)/_drop/$(Build.BuildId).zip"
      runtimeStack: "NODE|$(nodeLtsVersion)"
    displayName: "Deploy to Azure Web App"
